/* XTRARC.H */

#define ID_MAILRUNMAIN               11051
#define ID_MRAUTOCHECKSTART    11052
#define ID_MRAUTOCHECKSTOP      11053 
#define ID_MRCHECKNOW              11054 
#define ID_MRMINIMIZE                  11055
#define ID_MRMINIMIZENOW            11056
#define ID_MRQUIT                       11057
#define ID_MRSETTINGS                11058
#define ID_MRABOUT                    11059
#define ID_MRSTARTPROG             11060
#define ID_MRPREVIEW                  11061
#define ID_NETCHATSET                11062
